version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_new_postgres
    restart: always
    environment:
      POSTGRES_USER: ankur
      POSTGRES_PASSWORD: ankurpass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
